name: verdaccio e2e demo

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    name: setup verdaccio
    services:
      verdaccio:
        image: verdaccio/verdaccio:5
        ports:
          - 4873:4873

    steps:
    - uses: actions/checkout@v4
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: "22.x"
    - name: login
      run: npx npm-cli-login -u tester -p 123456 -e tester@example.com -r http://localhost:4873
    - name: publish
      run: npm publish --registry http://localhost:4873
      working-directory: .github/verdaccio/com.example.demo
    - name: check
      run: npm info com.example.demo --json --registry http://localhost:4873
      working-directory: .github/verdaccio/com.example.demo
