name: Publish Docker e2e.linux image
on:
  push:
    paths:
      - './docker/e2e.linux.Dockerfile'
  pull_request:
    paths:
      - './docker/e2e.linux.Dockerfile'
jobs:
  push_to_registry:
    name: Push Docker image to package registry
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}-e2e-linux:latest
