name: Publish e2e images
on:
  push: 
    paths:
      - "docker/e2e/**"
      - ".github/workflows/e2e-images.yml"

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: e2e-${{ github.repository }}

jobs: 
  publish_e2e_images:
    runs-on: ${{ matrix.os }}-latest
    
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
      
    strategy:
      matrix: 
        os:
          - ubuntu
          - windows
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build and push Docker image
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          tags: latest
          image: openupm-cli-e2e-${{matrix.os}}
          dockerfile: docker/e2e/${{matrix.os}}/Dockerfile
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
